#define p_WHITE_TAB_SPACE 0
#define p_SEMICOLON 1
#define p_PREPROCESSOR 2
#define p_SINGLE_LINE_COMMENT 3
#define p_MULTILINE_COMMENT 4
#define p_OPENING_BRACE 5
#define p_CLOSING_BRACE 6
#define p_FOR_MULTILINE 7
#define p_WHILE_MULTILINE 8
#define p_IF_MULTILINE 9
#define p_ELSE_IF_MULTILINE 10
#define p_ELSE_MULTILINE 11
#define p_FOR 12
#define p_WHILE 13
#define p_IF 14
#define p_ELSE_IF 15
#define p_ELSE 16
#define p_ENDOFFILE 17
#define p_STATEMENT 18
#define p_SWITCH 19
#define p_SWITCH_MULTILINE 20
#define p_CASE 21
#define p_CASE_MULTILINE 22
#define p_BREAK 23
#define p_CONTINUE 24
#define p_RETURN 25